project:
  type: website
  output-dir: docs

website:
  title: "Quiz 2 Website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: life-gdp.qmd
        text: Life Expectancy and GDP per Capita
      - href: life-population.qmd
        text: Life Expectancy and Population
      - href: country.qmd
        text: Country Analysis

format:
  html:
    theme: minty
    css: styles.css
    toc: true



